filter:
    paths: [src/*]
    excluded_paths: [vendor/*]
before_commands:
    - 'composer install --dev --prefer-dist'
tools:
    external_code_coverage:
        timeout: 600    # Timeout in seconds.
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_code_coverage: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests]
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, tests]
checks:
    php:
        code_rating: true
        duplication: true