services:
    hm.storage_manager:
        class: Dardarlt\Bundle\HangmanBundle\Manager\GameStorage
        arguments:
            - @doctrine

    hm.dictionary:
        class: Dardarlt\Bundle\HangmanBundle\Service\Dictionary
        arguments: ["@kernel"]

    hm.hangman_manager:
        class: Dardarlt\Bundle\HangmanBundle\Service\Hangman
        arguments: ["@hm.dictionary"]