services:
    hm.storage_manager:
        class: Dardarlt\Bundle\HangmanBundle\Manager\GameStorage
        arguments: ["@doctrine.orm.default_entity_manager"]

    hm.dictionary:
        class: Dardarlt\Bundle\HangmanBundle\Service\Dictionary

    hm.hangman_manager:
        class: Dardarlt\Bundle\HangmanBundle\Service\Hangman
        arguments: ["@hm.dictionary"]